baseurl = ""
title = "Ivan Pribec"
languageCode = "en-us"

# Theme to use
theme = "simple-hugo-theme"

# Pagination
[pagination]
  pagerSize = 3
  path = "page"

# Google analytics
# googleAnalytics = ""

# Copyright
copyright = "© 2019 — Ivan Pribec — All rights reserved."

# Highlighting
pygmentscodefences = true
pygmentscodefencesguessgyntax = false
pygmentsoptions = ""
pygmentsstyle = "vs"
pygmentsuseclasses = true

# Taxonomies
[taxonomies]
  tag = "tags"
  category = "categories"

# Menu
[menu]
  # Header
  [[menu.main]]
    url = "/posts/"
    name = "blog"
    weight = 1
  [[menu.main]]
    url = "/code/"
    name = "code"
    weight = 4
  [[menu.main]]
    url = "/diary/"
    name = "diary"
    weight = 4
  [[menu.main]]
    url = "/now/"
    name = "now"
    weight = 5

  # Footer
  [[menu.footer]]
    url = "https://github.com/ivan-pi"
    name = "GitHub"
    weight = 1
  [[menu.footer]]
    url = "/posts/index.xml"
    name = "RSS"
    weight = 2


# Links format
[permalinks]
  posts = "/posts/:year/:month/:title/"

[params]
  # Date format (default: Jan 2, 2006)
  # datefmt  = "Jan 2, 2006"
  # enable_katex = true
  katex = true
  custom_css = ["css/address.css"]
